### ISSUE TITLE
why  does the program ignore the three layers?

### ISSUE THREAD

**Issue by znsoftm** [skeskinen/bert.cpp#18]
In the convertion script, it ignores embeddings.position_ids

    if name in ['embeddings.position_ids', 'pooler.dense.weight', 'pooler.dense.bias']:
        continue

why?

**Comment by skeskinen** [comment]
position_ids is just list of integers, 0,1,2,3...
We can just recreate that at startup

**Comment by znsoftm** [comment]
thanks:)
