### ISSUE TITLE
convert 'chatglm-6b' model failed

### ISSUE THREAD

**Issue by lindeer** [skeskinen/bert.cpp#5]
Forgive me for my ignorance, seems 'chatglm-6b' is based on GLM framework, which is a BERT-style model. but its model repo does not contain `tokenizer.json` and `vocab.txt` and `python models/convert-to-ggml.py` failed. How could I make it possible to run with bert.cpp? thanks!

**Comment by skeskinen** [comment]
Hi, on a cursory look, GLM doesn't seem too close to BERT, so you'd probably have to change a lot of stuff. Also, chatglm looks like a primarily generative model and bert.cpp has only transformer encoder for producing sentence embeddings.
